version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pcelarstvo_mysql
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: pcel
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
